In [ ]:
import pandas as pd
from tqdm import tqdm
import numpy as np
site = r"/content/drive/MyDrive/miRNA/Circulation_data_seq/mesh.csv"
df = pd.read_csv(site)
df

root_disease                      discriptor_name all_discriptor_num
0     Breast Neoplasms                     Breast Neoplasms        C04.588.180
1     Breast Neoplasms                     Breast Neoplasms    C17.800.090.500
2     Breast Neoplasms                            Neoplasms                C04
3     Breast Neoplasms                    Neoplasms by Site            C04.588
4     Breast Neoplasms  Skin and Connective Tissue Diseases                C17
...                ...                                  ...                ...
5193      Chronic Pain                   Signs and Symptoms            C23.888
5194      Chronic Pain            Neurologic Manifestations        C23.888.592
5195      Chronic Pain                                 Pain    C23.888.592.612
5196           Allergy                     Hypersensitivity            C20.543
5197           Allergy               Immune System Diseases                C20

[5198 rows x 3 columns]

In [ ]:
df_test = df[(df['root_disease'] == 'Leukemia, Lymphocytic, Chronic, B-Cell')]
df_test

root_disease  \
73  Leukemia, Lymphocytic, Chronic, B-Cell   
74  Leukemia, Lymphocytic, Chronic, B-Cell   
75  Leukemia, Lymphocytic, Chronic, B-Cell   
76  Leukemia, Lymphocytic, Chronic, B-Cell   
77  Leukemia, Lymphocytic, Chronic, B-Cell   
78  Leukemia, Lymphocytic, Chronic, B-Cell   
79  Leukemia, Lymphocytic, Chronic, B-Cell   
80  Leukemia, Lymphocytic, Chronic, B-Cell   
81  Leukemia, Lymphocytic, Chronic, B-Cell   
82  Leukemia, Lymphocytic, Chronic, B-Cell   
83  Leukemia, Lymphocytic, Chronic, B-Cell   
84  Leukemia, Lymphocytic, Chronic, B-Cell   
85  Leukemia, Lymphocytic, Chronic, B-Cell   
86  Leukemia, Lymphocytic, Chronic, B-Cell   
87  Leukemia, Lymphocytic, Chronic, B-Cell   
88  Leukemia, Lymphocytic, Chronic, B-Cell   
89  Leukemia, Lymphocytic, Chronic, B-Cell   
90  Leukemia, Lymphocytic, Chronic, B-Cell   
91  Leukemia, Lymphocytic, Chronic, B-Cell   
92  Leukemia, Lymphocytic, Chronic, B-Cell   
93  Leukemia, Lymphocytic, Chronic, B-Cell   
94  Leukemia, Lymphocytic, Chronic, B-Cell   
95  Leukemia, Lymphocytic, Chronic, B-Cell   

                                discriptor_name       all_discriptor_num  
73       Leukemia, Lymphocytic, Chronic, B-Cell  C04.557.337.428.080.125  
74       Leukemia, Lymphocytic, Chronic, B-Cell  C15.604.515.560.080.125  
75       Leukemia, Lymphocytic, Chronic, B-Cell  C20.683.515.528.080.125  
76       Leukemia, Lymphocytic, Chronic, B-Cell      C23.550.291.500.483  
77                                    Neoplasms                      C04  
78                 Neoplasms by Histologic Type                  C04.557  
79                                     Leukemia              C04.557.337  
80                           Leukemia, Lymphoid          C04.557.337.428  
81                             Leukemia, B-Cell      C04.557.337.428.080  
82                 Hemic and Lymphatic Diseases                      C15  
83                           Lymphatic Diseases                  C15.604  
84                Lymphoproliferative Disorders              C15.604.515  
85                           Leukemia, Lymphoid          C15.604.515.560  
86                             Leukemia, B-Cell      C15.604.515.560.080  
87                       Immune System Diseases                      C20  
88                Immunoproliferative Disorders                  C20.683  
89                Lymphoproliferative Disorders              C20.683.515  
90                           Leukemia, Lymphoid          C20.683.515.528  
91                             Leukemia, B-Cell      C20.683.515.528.080  
92  Pathological Conditions, Signs and Symptoms                      C23  
93                         Pathologic Processes                  C23.550  
94                           Disease Attributes              C23.550.291  
95                              Chronic Disease          C23.550.291.500

In [ ]:
mesh_list = []
for i in range(len(df)):
  if df.iloc[i]['root_disease'] not in mesh_list: mesh_list.append(df.iloc[i]['root_disease'])
mesh_list

['Breast Neoplasms',
 'Carcinoma, Hepatocellular',
 'Lung Neoplasms',
 'Neoplasms [unspecific]',
 'Prostate Neoplasms',
 'Cardiomyopathy, Hypertrophic',
 'Schizophrenia',
 'Autoimmune Diseases [unspecific]',
 'Leukemia, Lymphocytic, Chronic, B-Cell',
 'Heart Failure',
 'Atopic Dermatitis',
 'Psoriasis',
 'Ovarian Neoplasms',
 'Musculoskeletal Abnormalities [unspecific]',
 'Retinitis Pigmentosa',
 'Alzheimer Disease',
 'Retinal Neovascularization',
 'Urinary Bladder Cancer',
 'Head And Neck Neoplasms',
 'Lymphoma, Burkitt',
 'Medulloblastoma',
 'Endometriosis',
 'Gastric Neoplasms',
 'Digestive System Neoplasms',
 'Astrocytoma',
 'Hepatitis B Virus Infection',
 'Carcinoma, Renal Cell',
 'Kaposi Sarcoma',
 'Lymphoma, Primary Effusion',
 'Endotoxemia',
 'Colorectal Carcinoma',
 'Primary Biliary Cirrhosis',
 'Salivary Gland Neoplasms',
 'Carcinoma, Adrenocortical',
 'Liver Diseases [unspecific]',
 'Bladder Neoplasms',
 'Essential Thrombocythemia',
 'Gastrointestinal Neoplasms',
 'Adrenal C

In [ ]:
max_len = 0
for i in range(len(df)):
  num = df.iloc[i]['all_discriptor_num'].split('.')
  if max_len < len(num): max_len = len(num)
max_len

9

In [ ]:
def num2name(df, num):
  return str(df[(df['all_discriptor_num']  == num)]['discriptor_name'].item())
disease = 'Leukemia, Lymphocytic, Chronic, B-Cell'
traget = df[(df['root_disease']  == disease)]
num2name(traget, 'C23.550.291.500')

'Chronic Disease'

In [ ]:
df[(df['root_disease']  == 'Leukemia, Lymphocytic, Chronic, B-Cell')]

root_disease  \
73  Leukemia, Lymphocytic, Chronic, B-Cell   
74  Leukemia, Lymphocytic, Chronic, B-Cell   
75  Leukemia, Lymphocytic, Chronic, B-Cell   
76  Leukemia, Lymphocytic, Chronic, B-Cell   
77  Leukemia, Lymphocytic, Chronic, B-Cell   
78  Leukemia, Lymphocytic, Chronic, B-Cell   
79  Leukemia, Lymphocytic, Chronic, B-Cell   
80  Leukemia, Lymphocytic, Chronic, B-Cell   
81  Leukemia, Lymphocytic, Chronic, B-Cell   
82  Leukemia, Lymphocytic, Chronic, B-Cell   
83  Leukemia, Lymphocytic, Chronic, B-Cell   
84  Leukemia, Lymphocytic, Chronic, B-Cell   
85  Leukemia, Lymphocytic, Chronic, B-Cell   
86  Leukemia, Lymphocytic, Chronic, B-Cell   
87  Leukemia, Lymphocytic, Chronic, B-Cell   
88  Leukemia, Lymphocytic, Chronic, B-Cell   
89  Leukemia, Lymphocytic, Chronic, B-Cell   
90  Leukemia, Lymphocytic, Chronic, B-Cell   
91  Leukemia, Lymphocytic, Chronic, B-Cell   
92  Leukemia, Lymphocytic, Chronic, B-Cell   
93  Leukemia, Lymphocytic, Chronic, B-Cell   
94  Leukemia, Lymphocytic, Chronic, B-Cell   
95  Leukemia, Lymphocytic, Chronic, B-Cell   

                                discriptor_name       all_discriptor_num  
73       Leukemia, Lymphocytic, Chronic, B-Cell  C04.557.337.428.080.125  
74       Leukemia, Lymphocytic, Chronic, B-Cell  C15.604.515.560.080.125  
75       Leukemia, Lymphocytic, Chronic, B-Cell  C20.683.515.528.080.125  
76       Leukemia, Lymphocytic, Chronic, B-Cell      C23.550.291.500.483  
77                                    Neoplasms                      C04  
78                 Neoplasms by Histologic Type                  C04.557  
79                                     Leukemia              C04.557.337  
80                           Leukemia, Lymphoid          C04.557.337.428  
81                             Leukemia, B-Cell      C04.557.337.428.080  
82                 Hemic and Lymphatic Diseases                      C15  
83                           Lymphatic Diseases                  C15.604  
84                Lymphoproliferative Disorders              C15.604.515  
85                           Leukemia, Lymphoid          C15.604.515.560  
86                             Leukemia, B-Cell      C15.604.515.560.080  
87                       Immune System Diseases                      C20  
88                Immunoproliferative Disorders                  C20.683  
89                Lymphoproliferative Disorders              C20.683.515  
90                           Leukemia, Lymphoid          C20.683.515.528  
91                             Leukemia, B-Cell      C20.683.515.528.080  
92  Pathological Conditions, Signs and Symptoms                      C23  
93                         Pathologic Processes                  C23.550  
94                           Disease Attributes              C23.550.291  
95                              Chronic Disease          C23.550.291.500

In [ ]:
def re_max_num(df, disease):
  target = list(df[(df['root_disease']  == disease)]['all_discriptor_num'])
  out = ""
  for item in target:
    if len(out) < len(item): out = item
  return str(df[(df['all_discriptor_num']  == out)]['discriptor_name'].item())


In [ ]:
def one_hot(index, max = 9):
  out = np.zeros(max)
  out[index-1] = 1
  return out
one_hot(3)

array([0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [ ]:
def mesh2graph(disease):
  node_list = []
  edge_list = []
  edge_attr_list = []
  traget = df[(df['root_disease']  == disease)]
  root_name = re_max_num(traget, disease)
  roots = list(traget[(traget['discriptor_name']  == root_name)]['all_discriptor_num'])
  root_name = root_name.replace(',', '')
  root_name = root_name.replace('-', ' ')
  node_list.append(root_name)
  pointer_from = 0



  for root in roots:
    num_list = root.split('.')
    pointer_to = 0
    distence_from_root = 1
    for i in range(len(num_list)-1):
      pointer_from += 1
      i += 1
      node = num2name(traget, '.'.join(num_list[:-i]))
      node = node.replace(',', '')
      node = node.replace('-', ' ')
      node_list.append(node)
      edge = [pointer_from, pointer_to]
      edge_list.append(edge)
      pointer_to = pointer_from
      edge_attr_list.append(one_hot(distence_from_root))
      distence_from_root += 1
  return node_list, edge_list, edge_attr_list

node_list, edge_list, edge_attr_list = mesh2graph('Leukemia, Lymphocytic, Chronic, B-Cell')
node = np.array(node_list)
edge = np.array(edge_list)
edge_attr = np.array(edge_attr_list)
print(node)
print(edge.T)
print(edge_attr)

['Leukemia Lymphocytic Chronic B Cell' 'Leukemia B Cell'
 'Leukemia Lymphoid' 'Leukemia' 'Neoplasms by Histologic Type' 'Neoplasms'
 'Leukemia B Cell' 'Leukemia Lymphoid' 'Lymphoproliferative Disorders'
 'Lymphatic Diseases' 'Hemic and Lymphatic Diseases' 'Leukemia B Cell'
 'Leukemia Lymphoid' 'Lymphoproliferative Disorders'
 'Immunoproliferative Disorders' 'Immune System Diseases'
 'Chronic Disease' 'Disease Attributes' 'Pathologic Processes'
 'Pathological Conditions Signs and Symptoms']
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  0  6  7  8  9  0 11 12 13 14  0 16 17 18]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0

In [ ]:
disease_list = []
for i in range(len(df)):
  disease = df.iloc[i]['root_disease']
  # disease = disease.replace(',', '')
  if disease not in disease_list: disease_list.append(disease)


In [ ]:
node_dict = {}
edge_dict = {}
edge_attr_dict = {}
for disease in disease_list:
  node_list, edge_list, edge_attr_list = mesh2graph(disease)
  node_dict[disease] = node_list
  edge_dict[disease] = edge_list
  edge_attr_dict[disease] = edge_attr_list
seed = 0
print(node_dict[disease_list[seed]])
print(edge_dict[disease_list[seed]])
print(edge_attr_dict[disease_list[seed]])

['Breast Neoplasms', 'Neoplasms by Site', 'Neoplasms', 'Breast Diseases', 'Skin Diseases', 'Skin and Connective Tissue Diseases']
[[1, 0], [2, 1], [3, 0], [4, 3], [5, 4]]
[array([1., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 1., 0., 0., 0., 0., 0., 0., 0.]), array([1., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 1., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 1., 0., 0., 0., 0., 0., 0.])]


In [ ]:
len(node_dict)

450

In [ ]:
seed = 269
print(node_dict[disease_list[seed]])
print(edge_dict[disease_list[seed]])
print(edge_attr_dict[disease_list[seed]])

['Mastitis', 'Puerperal Disorders', 'Pregnancy Complications', 'Female Urogenital Diseases and Pregnancy Complications', 'Urogenital Diseases', 'Breast Diseases', 'Skin Diseases', 'Skin and Connective Tissue Diseases']
[[1, 0], [2, 1], [3, 2], [4, 3], [5, 0], [6, 5], [7, 6]]
[array([1., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 1., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 1., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 1., 0., 0., 0., 0., 0.]), array([1., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 1., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 1., 0., 0., 0., 0., 0., 0.])]


In [ ]:
import pickle
files = open("/content/drive/MyDrive/miRNA/graph/node.pkl", "wb")
pickle.dump(node_dict, files)
files.close()
files = open("/content/drive/MyDrive/miRNA/graph/edge.pkl", "wb")
pickle.dump(edge_dict, files)
files.close()
files = open("/content/drive/MyDrive/miRNA/graph/edge_attr.pkl", "wb")
pickle.dump(edge_attr_dict, files)
files.close()